workspace:
  base: /go
  path: src/github.com/high-value-team/groupbox

pipeline:

  backend_build:
    image: golang:1.8
    environment:
      - MONGODB_URL=mongo:27017
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      - mkdir -p /go/src/github.com/high-value-team/groupbox/backend/bin
      - cp /go/src/github.com/high-value-team/groupbox/backend/build/template.docker.Dockerfile /go/src/github.com/high-value-team/groupbox/backend/bin/Dockerfile
      - cd /go/src/github.com/high-value-team/groupbox/backend/src
      - go build -o /go/src/github.com/high-value-team/groupbox/backend/bin/groupbox-backend .

  backend_docker:
    debug: true
    image: plugins/docker
    repo: hvt1/groupbox-backend
    secrets: [ docker_username, docker_password ]
    context: /go/src/github.com/high-value-team/groupbox/backend/bin
    dockerfile: /go/src/github.com/high-value-team/groupbox/backend/bin/Dockerfile

  backend_rancher:
    image: peloton/drone-rancher
    url: http://hvt.zone:8080/v1
    service: groupbox/backend
    docker_image: hvt1/groupbox-backend
    secrets: [ rancher_access_key, rancher_secret_key ]
    confirm: true
    timeout: 180

  frontend_build:
    image: node
    commands:
      - cd /go/src/github.com/high-value-team/groupbox/frontend/build
      - yarn install
      - npx run build_for_drone

  frontend_docker:
    debug: true
    image: plugins/docker
    repo: hvt1/groupbox-frontend
    secrets: [ docker_username, docker_password ]
    context: /go/src/github.com/high-value-team/groupbox/frontend/bin
    dockerfile: /go/src/github.com/high-value-team/groupbox/frontend/bin/Dockerfile

  frontend_rancher:
    image: peloton/drone-rancher
    url: http://hvt.zone:8080/v1
    service: groupbox/frontend
    docker_image: hvt1/groupbox-frontend
    secrets: [ rancher_access_key, rancher_secret_key ]
    confirm: true
    timeout: 180

services:
  mongo:
    image: mongo





